#!/usr/bin/env python
import MySQLdb

conn = MySQLdb.connect(host='192.168.128.1',user='gmm',passwd='infrasys',db='gmmenu',port=3306,charset='utf8')
cur = conn.cursor()
cur.execute("""DELETE FROM inf_images_objects""")
cur.execute("""DELETE FROM inf_item_categories""")
cur.execute("""DELETE FROM inf_items""")
cur.execute("""DELETE FROM inf_menu_lookup""")
cur.execute("""DELETE FROM inf_menus""")
cur.execute("""DELETE FROM inf_modifier_lists""")
cur.execute("""DELETE FROM inf_modifier_lookup""")
cur.execute("""DELETE FROM inf_modifiers""")
cur.execute("""DELETE FROM inf_outlets""")
cur.execute("""DELETE FROM inf_outlets_menus""")
cur.execute("""ALTER TABLE inf_images_objects AUTO_INCREMENT=1""")
cur.execute("""ALTER TABLE inf_item_categories AUTO_INCREMENT=1""")
cur.execute("""ALTER TABLE inf_items AUTO_INCREMENT=1""")
cur.execute("""ALTER TABLE inf_menu_lookup AUTO_INCREMENT=1""")
cur.execute("""ALTER TABLE inf_menus AUTO_INCREMENT=1""")
cur.execute("""ALTER TABLE inf_modifier_lists AUTO_INCREMENT=1""")
cur.execute("""ALTER TABLE inf_modifier_lookup AUTO_INCREMENT=1""")
cur.execute("""ALTER TABLE inf_modifiers AUTO_INCREMENT=1""")
cur.execute("""ALTER TABLE inf_outlets AUTO_INCREMENT=1""")
cur.execute("""ALTER TABLE inf_outlets_menus AUTO_INCREMENT=1""")
cur.close()
conn.close()
